name: "PROJECT-CHECK-FLUTTER"

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  flutter-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: "stable"

      - name: Inject secrets (Android)
        run: echo "kakao.nativeAppKey=${{ secrets.KAKAO_NATIVE_APP_KEY }}" >> android/local.properties

      - name: Inject secrets (iOS)
        run: echo "KAKAO_NATIVE_APP_KEY=${{ secrets.KAKAO_NATIVE_APP_KEY }}" > ios/Flutter/Secrets.xcconfig

      - name: Inject secrets (Dart)
        run: |
          cat > lib/core/config/app_secrets.dart << 'EOF'
          class AppSecrets {
            const AppSecrets._();
            static const String kakaoNativeAppKey = '${{ secrets.KAKAO_NATIVE_APP_KEY }}';
          }
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test
